# Generated by Django 2.0 on 2019-08-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lead_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leads.Lead_Category')),
            ],
        ),
        migrations.CreateModel(
            name='NewApplicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=400)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Send_To',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Institute', 'Institute'), ('All Institute', 'All Institute'), ('Company', 'Company'), ('All Company', 'All Company')], max_length=450)),
                ('lead_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leads.Lead_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CF', 'Sended')], default=1, max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='newapplicants',
            name='Send_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Leads.Send_To'),
        ),
        migrations.AddField(
            model_name='newapplicants',
            name='lead_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leads.Lead_Category'),
        ),
        migrations.AddField(
            model_name='newapplicants',
            name='leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Leads.Leads'),
        ),
        migrations.AddField(
            model_name='newapplicants',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Leads.Status'),
        ),
    ]
