# Generated by Django 2.0 on 2019-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
