# Generated by Django 2.0 on 2019-08-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0002_jobs_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Email', models.CharField(max_length=100, verbose_name='Email')),
                ('Contact', models.CharField(max_length=10, verbose_name='Contact')),
                ('Exp', models.CharField(max_length=100, verbose_name='Exp')),
                ('apply_Date', models.DateTimeField(auto_now_add=True, verbose_name='apply_Date')),
                ('Job_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.Jobs')),
            ],
        ),
    ]
